global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'vertex-ar-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/health/metrics'
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
